### ISSUE TITLE
Add `fail-mode` to list of options

### ISSUE THREAD

**Issue by 2stacks** [mrlesmithjr/ansible-openvswitch#2]
Not implementing `fail-mode` options fails with

```
failed: [metal-01.maas] (item={'bridge': 'br0', 'state': 'present', 'fail_mode': 'secure'}) => {"ansible_loop_var": "item", "changed": false, "cmd": "/usr/bin/ovs-vsctl -t 5 set-fail-mode br0 None", "item": {"bridge": "br0", "fail_mode": "secure", "state": "present"}, "msg": "ovs-vsctl: fail-mode must be \"standalone\" or \"secure\"", "rc": 1, "stderr": "ovs-vsctl: fail-mode must be \"standalone\" or \"secure\"\n", "stderr_lines": ["ovs-vsctl: fail-mode must be \"standalone\" or \"secure\""], "stdout": "", "stdout_lines": []}
```

[Docs](https://docs.ansible.com/ansible/latest/collections/openvswitch/openvswitch/openvswitch_bridge_module.html#parameter-fail_mode) do not indicate this field is required.

I was able to fix this by adding the following to `tasks/bridges.yml`
```
fail_mode: "{{ item['fail_mode']|default('standalone') }}"
```

I can open a pull request if you prefer.

**Comment by mrlesmithjr** [comment]
Hi @2stacks, thanks for reporting this. By all means PR's are more than welcomed!

**Comment by 2stacks** [comment]
Wasn't sure if you'd have a preference on default value.  `standalone` seems to be safest as `secure` is intended to be used with a controller http://www.openvswitch.org/support/dist-docs/ovs-vsctl.8.txt.  I'll open PR.
